// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: surface_level

#ifndef _SURFACE_LEVEL_UI_H
#define _SURFACE_LEVEL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_uispeedometer.h"
#include "ui_uigauge.h"
#include "ui_uiinclinometer.h"
#include "ui_uiScreenGame.h"
#include "ui_uilauncher.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_1093738210);   // assets/white-gray-abstract-contour-line-map (1) (1).png
LV_IMG_DECLARE( ui_img_1814113988);   // assets/jimny-logo-png_seeklogo-369021.png
LV_IMG_DECLARE( ui_img_85635262);   // assets/54108-200.png
LV_IMG_DECLARE( ui_img_engineload3_png);   // assets/engineload3.png
LV_IMG_DECLARE( ui_img_54439_png);   // assets/54439.png
LV_IMG_DECLARE( ui_img_1583778205);   // assets/ezgif-3e863e825e0d41f5.png
LV_IMG_DECLARE( ui_img_688645590);   // assets/ezgif-340fbbaa8934bc4c.png

// FONTS
LV_FONT_DECLARE( ui_font_rajdhani);
LV_FONT_DECLARE( ui_font_rajdhani1);
LV_FONT_DECLARE( ui_font_rajdhani200);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
