// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: surface_level

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void imageframe(lv_event_t * e);
void app_open_games_menu(lv_event_t * e);
void settings(lv_event_t * e);
void about(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
