// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: surface_level

#include "ui.h"

void zero_inclinometer(lv_event_t * e)
{
	extern void app_zero_inclinometer(lv_event_t*);
	app_zero_inclinometer(e);
}

void start_dino_game(lv_event_t * e)
{
	extern void app_start_dino_game(lv_event_t*);
	app_start_dino_game(e);
}

void dino_jump_trigger(lv_event_t * e)
{
	extern void app_dino_jump_trigger(lv_event_t*);
	app_dino_jump_trigger(e);
}

void imageframe(lv_event_t * e)
{
	extern void app_imageframe(lv_event_t*);
	app_imageframe(e);
}

void settings(lv_event_t * e)
{
	extern void app_settings(lv_event_t*);
	app_settings(e);
}

void app_open_games_menu(lv_event_t * e)
{
	extern void build_rom_menu();
	build_rom_menu();
}

void about(lv_event_t * e)
{
	extern void app_about(lv_event_t*);
	app_about(e);
}
