// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: surface_level

#include "ui.h"

lv_obj_t *ui_uilauncher = NULL;lv_obj_t *ui_Panel1 = NULL;lv_obj_t *ui_Buttonspeedometer = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Buttoninclinometer = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_Buttongauges = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_Buttonimageframe = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_Buttongame = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Buttonsettings = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_Buttonabout = NULL;lv_obj_t *ui_LabelAbout = NULL;lv_obj_t *ui_Container2 = NULL;lv_obj_t *ui_Image10 = NULL;lv_obj_t *ui_versionlabel = NULL;
// event funtions
void ui_event_Buttonspeedometer( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_uispeedometer, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_uispeedometer_screen_init);
}
}

void ui_event_Buttoninclinometer( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_uiinclinometer, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_uiinclinometer_screen_init);
}
}

void ui_event_Buttongauges( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_uigauge, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_uigauge_screen_init);
}
}

void ui_event_Buttonimageframe( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      imageframe( e );
}
}

void ui_event_Buttongame( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      app_open_games_menu( e );
}
}

void ui_event_Buttonsettings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      settings( e );
}
}

void ui_event_Buttonabout( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      about( e );
}
}

// build funtions

void ui_uilauncher_screen_init(void)
{
ui_uilauncher = lv_obj_create(NULL);
lv_obj_clear_flag( ui_uilauncher, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_uilauncher, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_uilauncher, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_uilauncher);
lv_obj_set_width( ui_Panel1, 427);
lv_obj_set_height( ui_Panel1, 331);
lv_obj_set_x( ui_Panel1, 0 );
lv_obj_set_y( ui_Panel1, 113 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_state( ui_Panel1, LV_STATE_FOCUSED );     /// States
lv_obj_set_scrollbar_mode(ui_Panel1, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Panel1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Panel1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Panel1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Panel1, 170, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Buttonspeedometer = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_Buttonspeedometer, 405);
lv_obj_set_height( ui_Buttonspeedometer, 83);
lv_obj_set_x( ui_Buttonspeedometer, 15 );
lv_obj_set_y( ui_Buttonspeedometer, 157 );
lv_obj_set_align( ui_Buttonspeedometer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Buttonspeedometer, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Buttonspeedometer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Buttonspeedometer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Buttonspeedometer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Buttonspeedometer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Buttonspeedometer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Buttonspeedometer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Buttonspeedometer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Buttonspeedometer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Buttonspeedometer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Buttonspeedometer);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Speedometer");
lv_obj_set_style_text_font(ui_Label1, &ui_font_rajdhani1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Buttoninclinometer = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_Buttoninclinometer, 405);
lv_obj_set_height( ui_Buttoninclinometer, 83);
lv_obj_set_x( ui_Buttoninclinometer, 15 );
lv_obj_set_y( ui_Buttoninclinometer, 157 );
lv_obj_set_align( ui_Buttoninclinometer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Buttoninclinometer, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Buttoninclinometer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Buttoninclinometer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Buttoninclinometer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Buttoninclinometer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Buttoninclinometer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Buttoninclinometer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Buttoninclinometer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Buttoninclinometer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Buttoninclinometer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Buttoninclinometer);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Inclinometer");
lv_obj_set_style_text_font(ui_Label3, &ui_font_rajdhani1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Buttongauges = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_Buttongauges, 405);
lv_obj_set_height( ui_Buttongauges, 83);
lv_obj_set_x( ui_Buttongauges, 15 );
lv_obj_set_y( ui_Buttongauges, 157 );
lv_obj_set_align( ui_Buttongauges, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Buttongauges, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Buttongauges, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Buttongauges, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Buttongauges, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Buttongauges, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Buttongauges, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Buttongauges, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Buttongauges, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Buttongauges, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Buttongauges, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_Buttongauges);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Gauges");
lv_obj_set_style_text_font(ui_Label4, &ui_font_rajdhani1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Buttonimageframe = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_Buttonimageframe, 405);
lv_obj_set_height( ui_Buttonimageframe, 83);
lv_obj_set_x( ui_Buttonimageframe, 15 );
lv_obj_set_y( ui_Buttonimageframe, 157 );
lv_obj_set_align( ui_Buttonimageframe, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Buttonimageframe, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Buttonimageframe, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Buttonimageframe, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Buttonimageframe, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Buttonimageframe, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Buttonimageframe, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Buttonimageframe, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Buttonimageframe, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Buttonimageframe, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Buttonimageframe, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Buttonimageframe);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Imageframe");
lv_obj_set_style_text_font(ui_Label5, &ui_font_rajdhani1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Buttongame = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_Buttongame, 405);
lv_obj_set_height( ui_Buttongame, 83);
lv_obj_set_x( ui_Buttongame, 15 );
lv_obj_set_y( ui_Buttongame, 157 );
lv_obj_set_align( ui_Buttongame, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Buttongame, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Buttongame, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Buttongame, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Buttongame, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Buttongame, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Buttongame, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Buttongame, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Buttongame, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Buttongame, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Buttongame, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_Buttongame);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Games");
lv_obj_set_style_text_font(ui_Label6, &ui_font_rajdhani1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Buttonsettings = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_Buttonsettings, 405);
lv_obj_set_height( ui_Buttonsettings, 83);
lv_obj_set_x( ui_Buttonsettings, 15 );
lv_obj_set_y( ui_Buttonsettings, 157 );
lv_obj_set_align( ui_Buttonsettings, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Buttonsettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Buttonsettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Buttonsettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Buttonsettings, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Buttonsettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Buttonsettings, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Buttonsettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Buttonsettings, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Buttonsettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Buttonsettings, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_Buttonsettings);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Settings");
lv_obj_set_style_text_font(ui_Label7, &ui_font_rajdhani1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Buttonabout = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_Buttonabout, 405);
lv_obj_set_height( ui_Buttonabout, 83);
lv_obj_set_x( ui_Buttonabout, 15 );
lv_obj_set_y( ui_Buttonabout, 157 );
lv_obj_set_align( ui_Buttonabout, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Buttonabout, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Buttonabout, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Buttonabout, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Buttonabout, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Buttonabout, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Buttonabout, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Buttonabout, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Buttonabout, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Buttonabout, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Buttonabout, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelAbout = lv_label_create(ui_Buttonabout);
lv_obj_set_width( ui_LabelAbout, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelAbout, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelAbout, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelAbout,"About");
lv_obj_set_style_text_font(ui_LabelAbout, &ui_font_rajdhani1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container2 = lv_obj_create(ui_uilauncher);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 508);
lv_obj_set_height( ui_Container2, 0); // Reverted height to 0
lv_obj_set_x( ui_Container2, -4 );
lv_obj_set_y( ui_Container2, -179 );
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );
lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT ); // Reverted to black
lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image10 = lv_img_create(ui_uilauncher);
lv_img_set_src(ui_Image10, &ui_img_1814113988);
lv_obj_set_width( ui_Image10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image10, 4 );
lv_obj_set_y( ui_Image10, -180 );
lv_obj_set_align( ui_Image10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image10, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_Image10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image10, 160);

ui_versionlabel = lv_label_create(ui_uilauncher);
lv_obj_set_width( ui_versionlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_versionlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_versionlabel, 0 );
lv_obj_set_y( ui_versionlabel, -125 );
lv_obj_set_align( ui_versionlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_versionlabel,"v1.0");
lv_obj_set_style_text_color(ui_versionlabel, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_versionlabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_versionlabel, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Buttonspeedometer, ui_event_Buttonspeedometer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Buttoninclinometer, ui_event_Buttoninclinometer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Buttongauges, ui_event_Buttongauges, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Buttonimageframe, ui_event_Buttonimageframe, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Buttongame, ui_event_Buttongame, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Buttonsettings, ui_event_Buttonsettings, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Buttonabout, ui_event_Buttonabout, LV_EVENT_ALL, NULL);

}

void ui_uilauncher_screen_destroy(void)
{
   if (ui_uilauncher) lv_obj_del(ui_uilauncher);

// NULL screen variables
ui_uilauncher= NULL;
ui_Panel1= NULL;
ui_Buttonspeedometer= NULL;
ui_Label1= NULL;
ui_Buttoninclinometer= NULL;
ui_Label3= NULL;
ui_Buttongauges= NULL;
ui_Label4= NULL;
ui_Buttonimageframe= NULL;
ui_Label5= NULL;
ui_Buttongame= NULL;
ui_Label6= NULL;
ui_Buttonsettings= NULL;
ui_Label7= NULL;
ui_Buttonabout= NULL;
ui_LabelAbout= NULL;
ui_Container2= NULL;
ui_Image10= NULL;
ui_versionlabel= NULL;

}
