// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: surface_level

#include "ui.h"

lv_obj_t *ui_uiScreenGame = NULL;
// event funtions
extern void stop_all_games(void);
extern void build_rom_menu(void);

void ui_event_uiScreenGame( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM  ) {
        lv_indev_wait_release(lv_indev_get_act());
        stop_all_games();
        build_rom_menu();
    }
}

// build funtions

void ui_uiScreenGame_screen_init(void)
{
ui_uiScreenGame = lv_obj_create(NULL);
lv_obj_clear_flag( ui_uiScreenGame, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_uiScreenGame, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_uiScreenGame, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_uiScreenGame, ui_event_uiScreenGame, LV_EVENT_ALL, NULL);

}

void ui_uiScreenGame_screen_destroy(void)
{
   if (ui_uiScreenGame) lv_obj_del(ui_uiScreenGame);

// NULL screen variables
ui_uiScreenGame= NULL;

}
