// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: surface_level

#include "ui.h"

lv_obj_t *ui_uigauge = NULL;lv_obj_t *ui_Image2 = NULL;lv_obj_t *ui_Image3 = NULL;lv_obj_t *ui_oiltemp = NULL;lv_obj_t *ui_oiltemplabel = NULL;lv_obj_t *ui_Engine_temp = NULL;lv_obj_t *ui_enginetemplabel = NULL;lv_obj_t *ui_batterylabel = NULL;lv_obj_t *ui_Batteryimg = NULL;lv_obj_t *ui_oiltempimg = NULL;lv_obj_t *ui_engintempimg = NULL;
// event funtions
void ui_event_uigauge( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if(lv_event_get_code(e) == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        extern void switch_to_launcher(); switch_to_launcher();
    }
}

// build funtions

void ui_uigauge_screen_init(void)
{
ui_uigauge = lv_obj_create(NULL);
lv_obj_clear_flag( ui_uigauge, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_uigauge, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_uigauge, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_uigauge);
lv_img_set_src(ui_Image2, &ui_img_1093738210);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image2, 0 );
lv_obj_set_y( ui_Image2, 0 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_opa(ui_Image2, 225, 0); // ~12% subdued, same as speedometer

ui_Image3 = lv_img_create(ui_uigauge);
lv_img_set_src(ui_Image3, &ui_img_1814113988);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image3, 0 );
lv_obj_set_y( ui_Image3, -180 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image3,200);
lv_obj_set_style_img_recolor(ui_Image3, lv_color_hex(0xAAAAAA), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_oiltemp = lv_arc_create(ui_uigauge);
lv_obj_set_width( ui_oiltemp, lv_pct(90));
lv_obj_set_height( ui_oiltemp, lv_pct(90));
lv_obj_set_align( ui_oiltemp, LV_ALIGN_CENTER );
lv_arc_set_value(ui_oiltemp, 67);
lv_arc_set_bg_angles(ui_oiltemp,120,230);
lv_obj_set_style_arc_width(ui_oiltemp, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_oiltemp, lv_color_hex(0x333333), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_opa(ui_oiltemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(ui_oiltemp, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_oiltemp, lv_color_hex(0xFFB020), LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_oiltemp, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_oiltemp, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_oiltemplabel = lv_label_create(ui_uigauge);
lv_obj_set_width( ui_oiltemplabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_oiltemplabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_oiltemplabel, -143 );
lv_obj_set_y( ui_oiltemplabel, 0 );
lv_obj_set_align( ui_oiltemplabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_oiltemplabel,"23%");
lv_obj_set_style_text_color(ui_oiltemplabel, lv_color_hex(0xFFB020), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_oiltemplabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_oiltemplabel, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Engine_temp = lv_arc_create(ui_uigauge);
lv_obj_set_width( ui_Engine_temp, lv_pct(90));
lv_obj_set_height( ui_Engine_temp, lv_pct(90));
lv_obj_set_align( ui_Engine_temp, LV_ALIGN_CENTER );
lv_arc_set_range(ui_Engine_temp, 40,120);
lv_arc_set_value(ui_Engine_temp, 53);
lv_arc_set_bg_angles(ui_Engine_temp,310,60);
lv_arc_set_mode(ui_Engine_temp, LV_ARC_MODE_REVERSE);
lv_obj_set_style_arc_width(ui_Engine_temp, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_Engine_temp, lv_color_hex(0x333333), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_opa(ui_Engine_temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(ui_Engine_temp, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_Engine_temp, lv_color_hex(0xFFB020), LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Engine_temp, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Engine_temp, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_enginetemplabel = lv_label_create(ui_uigauge);
lv_obj_set_width( ui_enginetemplabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_enginetemplabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_enginetemplabel, 136 );
lv_obj_set_y( ui_enginetemplabel, 0 );
lv_obj_set_align( ui_enginetemplabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_enginetemplabel,"53°c");
lv_obj_set_style_text_color(ui_enginetemplabel, lv_color_hex(0xFFB020), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_enginetemplabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_enginetemplabel, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batterylabel = lv_label_create(ui_uigauge);
lv_obj_set_width( ui_batterylabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batterylabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_batterylabel, 4 );
lv_obj_set_y( ui_batterylabel, 179 );
lv_obj_set_align( ui_batterylabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_batterylabel,"13.3v");
lv_obj_set_style_text_color(ui_batterylabel, lv_color_hex(0xFFB020), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_batterylabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_batterylabel, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Batteryimg = lv_img_create(ui_uigauge);
lv_img_set_src(ui_Batteryimg, &ui_img_85635262);
lv_obj_set_width( ui_Batteryimg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Batteryimg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Batteryimg, 0 );
lv_obj_set_y( ui_Batteryimg, 127 );
lv_obj_set_align( ui_Batteryimg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Batteryimg, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_Batteryimg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Batteryimg,80);
lv_obj_set_style_img_recolor(ui_Batteryimg, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Batteryimg, 140, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_oiltempimg = lv_img_create(ui_uigauge);
lv_img_set_src(ui_oiltempimg, &ui_img_engineload3_png);
lv_obj_set_width( ui_oiltempimg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_oiltempimg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_oiltempimg, -143 );
lv_obj_set_y( ui_oiltempimg, -78 );
lv_obj_set_align( ui_oiltempimg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_oiltempimg, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_oiltempimg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_oiltempimg,80);
lv_obj_set_style_img_recolor(ui_oiltempimg, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_oiltempimg, 140, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_engintempimg = lv_img_create(ui_uigauge);
lv_img_set_src(ui_engintempimg, &ui_img_54439_png);
lv_obj_set_width( ui_engintempimg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_engintempimg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_engintempimg, 135 );
lv_obj_set_y( ui_engintempimg, -80 );
lv_obj_set_align( ui_engintempimg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_engintempimg, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_engintempimg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_engintempimg,100);
lv_obj_set_style_img_recolor(ui_engintempimg, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_engintempimg, 140, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_uigauge, ui_event_uigauge, LV_EVENT_ALL, NULL);

}

void ui_uigauge_screen_destroy(void)
{
   if (ui_uigauge) lv_obj_del(ui_uigauge);

// NULL screen variables
ui_uigauge= NULL;
ui_Image2= NULL;
ui_Image3= NULL;
ui_oiltemp= NULL;
ui_oiltemplabel= NULL;
ui_Engine_temp= NULL;
ui_enginetemplabel= NULL;
ui_batterylabel= NULL;
ui_Batteryimg= NULL;
ui_oiltempimg= NULL;
ui_engintempimg= NULL;

}
