// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: surface_level

#ifndef UI_UIGAUGE_H
#define UI_UIGAUGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_uigauge
extern void ui_uigauge_screen_init(void);
extern void ui_uigauge_screen_destroy(void);
extern void ui_event_uigauge( lv_event_t * e);
extern lv_obj_t *ui_uigauge;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_oiltemp;
extern lv_obj_t *ui_oiltemplabel;
extern lv_obj_t *ui_Engine_temp;
extern lv_obj_t *ui_enginetemplabel;
extern lv_obj_t *ui_batterylabel;
extern lv_obj_t *ui_Batteryimg;
extern lv_obj_t *ui_oiltempimg;
extern lv_obj_t *ui_engintempimg;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

