// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: surface_level
#include "ui.h"
#include "ui_godzillaspeedometer.h"

lv_obj_t *ui_uispeedometer = NULL;
lv_obj_t *ui_Image9 = NULL;
lv_obj_t *ui_rpmlabel = NULL;
lv_obj_t *ui_speedlabel = NULL;
lv_obj_t *ui_rpmarc = NULL;
lv_obj_t *ui_Image8 = NULL;
lv_obj_t *ui_visspeed = NULL;
lv_obj_t *ui_visrpm = NULL;

bool is_standard_animating = false;

static void standard_anim_cb(void * var, int32_t v) {
    if (ui_rpmarc) {
        lv_arc_set_value(ui_rpmarc, v);

        // Color zones: amber (<3000), hot (<6000), redline (>=6000) — matches
        // the live-operation zones in screen_ui.h's get_rpm_gauge_color() and
        // the redline sector/tick boundary in build_speedo_rpm_gauge() (both
        // at 6000), so the boot-sweep animation previews the same colors
        // real driving will show, instead of a different yellow/blue/red set.
        uint32_t color_hex = 0xFFB020;
        if (v < 3000) {
            color_hex = 0xFFB020; // amber
        } else if (v < 6000) {
            color_hex = 0xFFC54D; // hot
        } else {
            color_hex = 0xFF3B1D; // redline
        }
        lv_obj_set_style_arc_color(ui_rpmarc, lv_color_hex(color_hex), LV_PART_INDICATOR);

        // Speed and rpm values both follow the same zone as the arc (matches
        // the live update logic in screen_ui.h's update_screen_ui()) — only
        // the unit captions stay fixed amber.
        if (ui_speedlabel) {
            lv_obj_set_style_text_color(ui_speedlabel, lv_color_hex(color_hex), LV_PART_MAIN);
        }
        if (ui_rpmlabel) {
            lv_obj_set_style_text_color(ui_rpmlabel, lv_color_hex(color_hex), LV_PART_MAIN);
        }
    }
    if (ui_rpmlabel) {
        lv_label_set_text_fmt(ui_rpmlabel, "%d", (int)v);
    }
    if (ui_speedlabel) {
        int32_t speed = (v * 140) / 8000;
        lv_label_set_text_fmt(ui_speedlabel, "%d", (int)speed);
    }
}

static void standard_anim_ready_cb(lv_anim_t * a) {
    is_standard_animating = false;
}

// event functions
void ui_event_uispeedometer(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        is_standard_animating = true;
        lv_anim_t a;
        lv_anim_init(&a);
        lv_anim_set_var(&a, ui_rpmarc);
        lv_anim_set_values(&a, 0, 8000);
        lv_anim_set_time(&a, 2200); 
        lv_anim_set_playback_time(&a, 1200); 
        lv_anim_set_delay(&a, 500);
        lv_anim_set_repeat_count(&a, 1);
        lv_anim_set_exec_cb(&a, standard_anim_cb);
        lv_anim_set_ready_cb(&a, standard_anim_ready_cb);
        lv_anim_set_path_cb(&a, lv_anim_path_ease_in_out);
        lv_anim_start(&a);
    }

    if(lv_event_get_code(e) == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        extern void switch_to_launcher(); switch_to_launcher();
    }
    
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_godzillaspeedometer, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_godzillaspeedometer_screen_init);
    }
    if (event_code == LV_EVENT_LONG_PRESSED) {
        open_speedo_settings_menu(ui_uispeedometer, false);
    }
}

// build functions
void ui_uispeedometer_screen_init(void)
{
ui_uispeedometer = lv_obj_create(NULL);
lv_obj_clear_flag( ui_uispeedometer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_flag( ui_uispeedometer, LV_OBJ_FLAG_CLICKABLE ); // Clickable for long press detection
lv_obj_set_style_bg_color(ui_uispeedometer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_uispeedometer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image9 = lv_img_create(ui_uispeedometer);
lv_img_set_src(ui_Image9, &ui_img_1093738210);
lv_obj_set_width( ui_Image9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image9, 0 );
lv_obj_set_y( ui_Image9, 0 );
lv_obj_set_align( ui_Image9, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Image9, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_Image9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
// ui_img_1093738210 is now native 466x466 (was a 200x199 stock texture
// needing 800/256x zoom + heavy black recolor to fill the screen and tone
// it down) — no zoom/recolor needed, the new artwork is already screen-fit
// and dark on its own.

ui_rpmlabel = lv_label_create(ui_uispeedometer);
lv_obj_set_width( ui_rpmlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rpmlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_rpmlabel, -37 );
lv_obj_set_y( ui_rpmlabel, 179 );
lv_obj_set_align( ui_rpmlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_rpmlabel,"3500");
lv_obj_set_style_text_color(ui_rpmlabel, lv_color_hex(0xFFB020), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_rpmlabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_rpmlabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_speedlabel = lv_label_create(ui_uispeedometer);
lv_obj_set_width( ui_speedlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_speedlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_speedlabel, 0 );
lv_obj_set_y( ui_speedlabel, 4 );
lv_obj_set_align( ui_speedlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_speedlabel,"65");
lv_obj_set_style_text_color(ui_speedlabel, lv_color_hex(0xFFB020), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_speedlabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_speedlabel, &ui_font_rajdhani200, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rpmarc = lv_arc_create(ui_uispeedometer);
lv_obj_set_width( ui_rpmarc, lv_pct(90));
lv_obj_set_height( ui_rpmarc, lv_pct(90));
lv_obj_set_align( ui_rpmarc, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_rpmarc, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_arc_set_range(ui_rpmarc, 0,8000);
lv_arc_set_value(ui_rpmarc, 3500);

lv_obj_set_style_arc_color(ui_rpmarc, lv_color_hex(0xFFB020), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_rpmarc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_rpmarc, 14, LV_PART_INDICATOR | LV_STATE_DEFAULT); // make arc slightly thicker

lv_obj_set_style_bg_color(ui_rpmarc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rpmarc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_clear_flag(ui_rpmarc, LV_OBJ_FLAG_CLICKABLE);

ui_Image8 = lv_img_create(ui_uispeedometer);
lv_img_set_src(ui_Image8, &ui_img_1814113988);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image8, -1 );
lv_obj_set_y( ui_Image8, -122 );
lv_obj_set_align( ui_Image8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image8,150);
lv_obj_set_style_img_recolor(ui_Image8, lv_color_hex(0xAAAAAA), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_visspeed = lv_label_create(ui_uispeedometer);
lv_obj_set_width( ui_visspeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_visspeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_visspeed, 3 );
lv_obj_set_y( ui_visspeed, 98 );
lv_obj_set_align( ui_visspeed, LV_ALIGN_CENTER );
lv_label_set_text(ui_visspeed,"km/h");
lv_obj_set_style_text_color(ui_visspeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_visspeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_visspeed, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_visrpm = lv_label_create(ui_uispeedometer);
lv_obj_set_width( ui_visrpm, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_visrpm, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_visrpm, 68 );
lv_obj_set_y( ui_visrpm, 180 );
lv_obj_set_align( ui_visrpm, LV_ALIGN_CENTER );
lv_label_set_text(ui_visrpm,"rpm");
lv_obj_set_style_text_color(ui_visrpm, lv_color_hex(0xFFB020), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_visrpm, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_visrpm, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_uispeedometer, ui_event_uispeedometer, LV_EVENT_ALL, NULL);

// Pagination Dot Indicator (Left Active - 2 Dots)
lv_obj_t * pag_dots_container = lv_obj_create(ui_uispeedometer);
lv_obj_set_size(pag_dots_container, 60, 20);
lv_obj_align(pag_dots_container, LV_ALIGN_BOTTOM_MID, 0, -12);
lv_obj_set_style_bg_opa(pag_dots_container, 0, 0);
lv_obj_set_style_border_width(pag_dots_container, 0, 0);
lv_obj_set_style_pad_all(pag_dots_container, 0, 0);
lv_obj_clear_flag(pag_dots_container, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_CLICKABLE);

lv_obj_t * dot_std = lv_obj_create(pag_dots_container);
lv_obj_set_size(dot_std, 8, 8);
lv_obj_align(dot_std, LV_ALIGN_CENTER, -10, 0);
lv_obj_set_style_radius(dot_std, LV_RADIUS_CIRCLE, 0);
lv_obj_set_style_bg_color(dot_std, lv_color_hex(0xFF9500), 0); // Active
lv_obj_set_style_border_width(dot_std, 0, 0);
lv_obj_clear_flag(dot_std, LV_OBJ_FLAG_CLICKABLE);

lv_obj_t * dot_godz = lv_obj_create(pag_dots_container);
lv_obj_set_size(dot_godz, 8, 8);
lv_obj_align(dot_godz, LV_ALIGN_CENTER, 10, 0);
lv_obj_set_style_radius(dot_godz, LV_RADIUS_CIRCLE, 0);
lv_obj_set_style_bg_color(dot_godz, lv_color_hex(0x444444), 0); // Dimmed
lv_obj_set_style_border_width(dot_godz, 0, 0);
lv_obj_clear_flag(dot_godz, LV_OBJ_FLAG_CLICKABLE);

}

void ui_uispeedometer_screen_destroy(void)
{
   if (ui_uispeedometer) lv_obj_del(ui_uispeedometer);

// NULL screen variables
ui_uispeedometer= NULL;
ui_Image9= NULL;
ui_rpmlabel= NULL;
ui_speedlabel= NULL;
ui_rpmarc= NULL;
ui_Image8= NULL;
ui_visspeed= NULL;
ui_visrpm= NULL;

}
