// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: surface_level

#ifndef UI_UIINCLINOMETER_H
#define UI_UIINCLINOMETER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_uiinclinometer
extern void ui_uiinclinometer_screen_init(void);
extern void ui_uiinclinometer_screen_destroy(void);
extern void ui_event_uiinclinometer( lv_event_t * e);
extern lv_obj_t *ui_uiinclinometer;
extern lv_obj_t *ui_Image7;
extern lv_obj_t *ui_CarRollImg;
extern lv_obj_t *ui_uiimgRoll;
extern lv_obj_t *ui_CarPitchImg;
extern lv_obj_t *ui_uiimgPitch;
extern lv_obj_t *ui_Engine_temp2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

