// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: surface_level

#ifndef UI_UILAUNCHER_H
#define UI_UILAUNCHER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_uilauncher
extern void ui_uilauncher_screen_init(void);
extern void ui_uilauncher_screen_destroy(void);
extern lv_obj_t *ui_uilauncher;
extern lv_obj_t *ui_Panel1;
extern void ui_event_Buttonspeedometer( lv_event_t * e);
extern lv_obj_t *ui_Buttonspeedometer;
extern lv_obj_t *ui_Label1;
extern void ui_event_Buttoninclinometer( lv_event_t * e);
extern lv_obj_t *ui_Buttoninclinometer;
extern lv_obj_t *ui_Label3;
extern void ui_event_Buttongauges( lv_event_t * e);
extern lv_obj_t *ui_Buttongauges;
extern lv_obj_t *ui_Label4;
extern void ui_event_Buttonimageframe( lv_event_t * e);
extern lv_obj_t *ui_Buttonimageframe;
extern lv_obj_t *ui_Label5;
extern void ui_event_Buttongame( lv_event_t * e);
extern lv_obj_t *ui_Buttongame;
extern lv_obj_t *ui_Label6;
extern void ui_event_Buttonsettings( lv_event_t * e);
extern lv_obj_t *ui_Buttonsettings;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Image10;
extern lv_obj_t *ui_versionlabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

