// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: surface_level

#ifndef UI_UISPEEDOMETER_H
#define UI_UISPEEDOMETER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_uispeedometer
extern void ui_uispeedometer_screen_init(void);
extern void ui_uispeedometer_screen_destroy(void);
extern void ui_event_uispeedometer( lv_event_t * e);
extern lv_obj_t *ui_uispeedometer;
extern lv_obj_t *ui_Image9;
extern lv_obj_t *ui_rpmlabel;
extern lv_obj_t *ui_speedlabel;
extern lv_obj_t *ui_rpmarc;
extern lv_obj_t *ui_Image8;
extern lv_obj_t *ui_visspeed;
extern lv_obj_t *ui_visrpm;
// CUSTOM VARIABLES
extern bool is_standard_animating;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

