// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: surface_level

#ifndef UI_UISCREENGAME_H
#define UI_UISCREENGAME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_uiScreenGame
extern void ui_uiScreenGame_screen_init(void);
extern void ui_uiScreenGame_screen_destroy(void);
extern void ui_event_uiScreenGame( lv_event_t * e);
extern lv_obj_t *ui_uiScreenGame;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

