// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: surface_level

#include "ui.h"

lv_obj_t *ui_uiinclinometer = NULL;lv_obj_t *ui_Image7 = NULL;lv_obj_t *ui_CarRollImg = NULL;lv_obj_t *ui_uiimgRoll = NULL;lv_obj_t *ui_CarPitchImg = NULL;lv_obj_t *ui_uiimgPitch = NULL;lv_obj_t *ui_Engine_temp2 = NULL;
// event funtions
void ui_event_uiinclinometer( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if(lv_event_get_code(e) == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        extern void switch_to_launcher(); switch_to_launcher();
    }
}

// build funtions

void ui_uiinclinometer_screen_init(void)
{
ui_uiinclinometer = lv_obj_create(NULL);
lv_obj_clear_flag( ui_uiinclinometer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_uiinclinometer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_uiinclinometer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image7 = lv_img_create(ui_uiinclinometer);
lv_img_set_src(ui_Image7, &ui_img_1814113988);
lv_obj_set_width( ui_Image7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image7, 4 );
lv_obj_set_y( ui_Image7, -180 );
lv_obj_set_align( ui_Image7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image7, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_Image7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image7,200);
lv_obj_set_style_img_recolor(ui_Image7, lv_color_hex(0xAAAAAA), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CarRollImg = lv_img_create(ui_uiinclinometer);
lv_img_set_src(ui_CarRollImg, &ui_img_1583778205);
lv_obj_set_width( ui_CarRollImg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CarRollImg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CarRollImg, 0 );
lv_obj_set_y( ui_CarRollImg, -69 );
lv_obj_set_align( ui_CarRollImg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CarRollImg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_CarRollImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_uiimgRoll = lv_label_create(ui_uiinclinometer);
lv_obj_set_width( ui_uiimgRoll, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiimgRoll, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiimgRoll, 0 );
lv_obj_set_y( ui_uiimgRoll, -3 );
lv_obj_set_align( ui_uiimgRoll, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_uiimgRoll, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiimgRoll, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiimgRoll, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CarPitchImg = lv_img_create(ui_uiinclinometer);
lv_img_set_src(ui_CarPitchImg, &ui_img_688645590);
lv_obj_set_width( ui_CarPitchImg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CarPitchImg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CarPitchImg, 0 );
lv_obj_set_y( ui_CarPitchImg, 91 );
lv_obj_set_align( ui_CarPitchImg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CarPitchImg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_CarPitchImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_uiimgPitch = lv_label_create(ui_uiinclinometer);
lv_obj_set_width( ui_uiimgPitch, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiimgPitch, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiimgPitch, 0 );
lv_obj_set_y( ui_uiimgPitch, 156 );
lv_obj_set_align( ui_uiimgPitch, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_uiimgPitch, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiimgPitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiimgPitch, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Engine_temp2 = lv_arc_create(ui_uiinclinometer);
lv_obj_set_width( ui_Engine_temp2, lv_pct(90));
lv_obj_set_height( ui_Engine_temp2, lv_pct(90));
lv_obj_set_align( ui_Engine_temp2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Engine_temp2, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_arc_set_value(ui_Engine_temp2, 53);
lv_arc_set_bg_angles(ui_Engine_temp2,320,220);
lv_arc_set_mode(ui_Engine_temp2, LV_ARC_MODE_REVERSE);
lv_obj_set_style_bg_color(ui_Engine_temp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Engine_temp2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Engine_temp2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Engine_temp2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Engine_temp2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Engine_temp2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Engine_temp2, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Engine_temp2, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Engine_temp2, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Engine_temp2, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Engine_temp2, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_Engine_temp2, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Engine_temp2, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Engine_temp2, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Engine_temp2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Engine_temp2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Engine_temp2, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Engine_temp2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Engine_temp2, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Engine_temp2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_uiinclinometer, ui_event_uiinclinometer, LV_EVENT_ALL, NULL);

}

void ui_uiinclinometer_screen_destroy(void)
{
   if (ui_uiinclinometer) lv_obj_del(ui_uiinclinometer);

// NULL screen variables
ui_uiinclinometer= NULL;
ui_Image7= NULL;
ui_CarRollImg= NULL;
ui_uiimgRoll= NULL;
ui_CarPitchImg= NULL;
ui_uiimgPitch= NULL;
ui_Engine_temp2= NULL;

}
